### ISSUE TITLE
Does this support file saving after scaning?

### ISSUE THREAD

**Issue by NayanVaid** [AugustoPinheiro/RN-react-native-document-scanner#4]
Does this support file saving after scanning or we have to use other library?

**Comment by AugustoPinheiro** [comment]
What do you want to do, can you explain better?

**Comment by NayanVaid** [comment]
I want to save the pdf file after it is scanned. Thank you for your response :D

**Comment by AugustoPinheiro** [comment]
> I want to save the pdf file after it is scanned. Thank you for your response :D

You need to get image URI After

`https://github.com/Anyline/react-native-image-to-pdf
`

use this component for convert image to pdf...

**Comment by AugustoPinheiro** [comment]
it's a pleasure to help :)

**Comment by NayanVaid** [comment]
Does this works with expo? How can I get the scanned image uri? Thank you :D

**Comment by AugustoPinheiro** [comment]
You can find the response with 64Base URI


<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(173, 186, 199); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Properties</h2>

Prop | Platform | Default | Type | Description
-- | -- | -- | -- | --
overlayColor | Both | none | string | Color of the detected rectangle : rgba recommended
detectionCountBeforeCapture | Both | 5 | integer | Number of correct rectangle to detect before capture
detectionRefreshRateInMS | iOS | 50 | integer | Time between two rectangle detection attempt
enableTorch | Both | false | bool | Allows to active or deactivate flash during document detection
useFrontCam | iOS | false | bool | Allows you to switch between front and back camera
brightness | iOS | 0 | float | Increase or decrease camera brightness. Normal as default.
saturation | iOS | 1 | float | Increase or decrease camera saturation. Set 0 for black & white
contrast | iOS | 1 | float | Increase or decrease camera contrast. Normal as default
quality | iOS | 0.8 | float | Image compression. Reduces both image size and quality
useBase64 | iOS | false | bool | If base64 representation should be passed instead of image uri's
saveInAppDocument | iOS | false | bool | If should save in app document in case of not using base 64
captureMultiple | iOS | false | bool | Keeps the scanner on after a successful capture
onPermissionsDenied | android | null | func | Function to call when the Android permissions are denied

<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(173, 186, 199); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-manual-capture" class="anchor" aria-hidden="true" href="https://github.com/Michaelvilleneuve/react-native-document-scanner#manual-capture" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none; float: left; line-height: 1; margin-left: -20px; padding-right: 4px;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a></h2><br class="Apple-interchange-newline">

**Comment by NayanVaid** [comment]
Thank you soo much :D Just one last question. Does this works wih expo?

**Comment by AugustoPinheiro** [comment]
`saveInAppDocument
`

<br class="Apple-interchange-newline">
demo:

![image](https://user-images.githubusercontent.com/33337164/129467133-6be7c8e4-2265-4462-9a61-2374079b4c51.png)


With this new feature, we can now save images into app document, and then see them directly into the apple file explore







> You can find the response with 64Base URI
> 
> ## Properties
> Prop	Platform	Default	Type	Description
> overlayColor	Both	none	string	Color of the detected rectangle : rgba recommended
> detectionCountBeforeCapture	Both	5	integer	Number of correct rectangle to detect before capture
> detectionRefreshRateInMS	iOS	50	integer	Time between two rectangle detection attempt
> enableTorch	Both	false	bool	Allows to active or deactivate flash during document detection
> useFrontCam	iOS	false	bool	Allows you to switch between front and back camera
> brightness	iOS	0	float	Increase or decrease camera brightness. Normal as default.
> saturation	iOS	1	float	Increase or decrease camera saturation. Set 0 for black & white
> contrast	iOS	1	float	Increase or decrease camera contrast. Normal as default
> quality	iOS	0.8	float	Image compression. Reduces both image size and quality
> useBase64	iOS	false	bool	If base64 representation should be passed instead of image uri's
> saveInAppDocument	iOS	false	bool	If should save in app document in case of not using base 64
> captureMultiple	iOS	false	bool	Keeps the scanner on after a successful capture
> onPermissionsDenied	android	null	func	Function to call when the Android permissions are denied
> ##

**Comment by AugustoPinheiro** [comment]
> Thank you soo much :D Just one last question. Does this works wih expo?

dont works in yet, but I have plans to support Expo

**Comment by NayanVaid** [comment]
Thank you soo much :D Eagerly waiting for expo support! Keep up the good work!
